name: Remove PR Labels

on:
  pull_request_target:
    types: ["closed"]

permissions:
  contents: read

jobs:
  remove-label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
      with:
        egress-policy: audit

    - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
      with:
        labels: |
          awaiting-PR-merge
          awaiting-review